services:

  db-wiki:
    build: ./postgres
    env_file: "./postgres/bd-postgres.conf"
    volumes:
      - wikijs_db-data:/var/lib/postgresql
    networks:
      - net-res
  wiki:
    build: ./wiki
    depends_on:
      - db-wiki
    env_file: "./wiki/wiki-conf.env"
    ports:
      - "8080:3000"
      - "443:3443"
    networks:
    - net-res

networks:
  net-res:

volumes:
  db-data:
# Remplacer les lignes présentes dans volumes par celle ci : 
#
#wikijs_db-data:
#    external: true
#